### ISSUE TITLE
New Region: Targon

### ISSUE THREAD

**Issue by z4r** [MisterVants/RuneterraDecks#1]
Hi @MisterVants ,
with the 3rd set LoR has a new region: Targon. Its identifier in the `cardCode` is `MT`.
I can proceed with a PR, but i don't know if the index of the `enum Faction` is an auto count.

On this ruby library is `9`: https://github.com/zofrex/runeterra_cards/blob/development/lib/runeterra_cards/factions.rb

Thx in advance

**Comment by dukevantreta** [comment]
Hey @z4r ,
Following the official Riot docs, Targon index is indeed `9`. The `enum Faction` is not auto counted, a new case can be added with an arbitrary index. I believe its all good for a PR!
